language: node_js
os:
  - windows
  # - linux
node_js:
  # - lts/dubnium
  - node
script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm test; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run test-api; fi
after_script:
  - bash <(curl -s https://codecov.io/bash)
